### ISSUE TITLE
No anonymous login possible

### ISSUE THREAD

**Issue by Oli72** [whyorean/AuroraStore#43]
At the moment, both 4.2.2 and 4.1.1 (on two different devices) cannot login anonymously.
Does anyone experience the same issue?

**Comment by salustre** [comment]
Same here

**Comment by DarkCrypt** [comment]
This issue is very well known. App updates still work for many users by bypassing login screen.

Learn more, stay updated, and post issues at the official GitLab repo: [Aurora Store - Official](https://gitlab.com/AuroraOSS/AuroraStore)

Anonymous login issue at GitLab: [#912](https://gitlab.com/AuroraOSS/AuroraStore/-/issues/912)

**Comment by salustre** [comment]
Thanks @DarkCrypt I will track the GitLab repo then.

**Comment by DarkCrypt** [comment]
@salustre 
No problem. You've probably already noticed but you can login at GitLab with your GitHub account.

**Comment by DarkCrypt** [comment]
@Oli72 
Just letting you know the devs fixed this issue. Anonymous login is working.

**Comment by Oli72** [comment]
Thanks!
