### ISSUE TITLE
Aurora store wants to update apps that are not even installed on the device!

### ISSUE THREAD

**Issue by pitsi** [whyorean/AuroraStore#44]
A couple of days ago, I installed crdroid 8.2 (official release, android 12 based) on a samsung a40. Through twrp, I wiped all the requested partitions (data, system, cache, vendor, product) and installed the rom. I did not install any sort of gapps or magisk for root, so it is just a plain, ungoogled device without root.

Then I installed aurora store from fdroid (via fdroidcl) and when I launched it I came accross these 2 "updates"! And I can't even "uninstall" them (select each one > 3 dots menu at top right > uninstall)
![Screenshot_20230603-135559_Aurora Store](https://github.com/whyorean/AuroraStore/assets/5880037/d7a7133a-edfd-4adc-a118-e672c3fc8d58)

Assuming that before the wipe the device had all of google's garbage apps, I can justify the device health services app. But the other one is completely unknown. If it helps, these are all the installed packages on the device (adb shell pm list packages)

https://paste.debian.net/hidden/8abe52dd/

I also use aurora store on my old tab running lineage 14.2 (with root priviledges) and on my nokia 5 running android 9 (no root) and I have zero issues there. However, I installed aurora store from the apk on its official page on those 2.
I use aurora store with the anonymous login option on all 3.

**Comment by DarkCrypt** [comment]
This is a mirror repo, I wouldn't expect a response from the dev.

**OFFICIAL REPO ->** GitLab: [Aurora Store - Official Repo](https://gitlab.com/AuroraOSS/AuroraStore)

You can login at GitLab with your GitHub account.

**Comment by pitsi** [comment]
I know that and you are right. I just posted in case any other user has an idea on what it might be.
Moreover, I do not use the "login with (insert a popular site here)" method anywhere.

On the other hand, I think I found it. Those 2 packages that aurora wants to update are in the list as 
```
package:com.google.android.apps.turbo
package:com.footej.camera2
```
The first one is a google app, nothing weird about that. But why is a google app included in an aosp based rom?
The second one is the... default camera app! How come it has the same package name as a closed source app?!

I will close the issue in the following days. If anyone can confirm my thought above, please post. Thank you :)

**Comment by DarkCrypt** [comment]
> I know that and you are right. I just posted in case any other user has an idea on what it might be. Moreover, I do not use the "login with (insert a popular site here)" method anywhere.

Sorry, I don't know who knows and who doesn't know about official repo. I've been posting everywhere because some users don't know. If you don't want to participate in the actual repo where all the engagement is by users and devs then that's your choice.

To attempt to help answer your posts...

> package:com.google.android.apps.turbo
package:com.footej.camera2

You're correct about the 2 packages in question. The app names from the screenshot match the package IDs. You can easily find out this info and more by utilizing any decent app manager, search on APKMirror, or type the package ID into a search engine. Since you wiped your device and installed crdroid, these apps definitely came preinstalled within crdroid.

> The first one is a google app, nothing weird about that. But why is a google app included in an aosp based rom?

That's a good question for the crdroid team but probably because they like that app. Just because the rom is aosp doesn't mean it's automatically Google free. Stock Android is aosp and also not Google free. The only aosp roms I've seen that are Google free explicitly state they are or at least say users must install Gapps if you want Google's crap.

> The second one is the... default camera app! How come it has the same package name as a closed source app?!

Probably because it's the exact same closed source app. Apparently crdroid likes that app also.

If you've tried different ways to uninstall these apps and are still unsuccessful, you can uninstall them with adb.

On a side note: I prefer using Aurora Store with my own fake Google account because it seems to be better than sharing anonymous accounts.

**Comment by pitsi** [comment]
Thank you for all the info :)
I will ask at the crdroid github repo.

**Comment by pitsi** [comment]
For the record, I reflashed the rom and this time I installed some gapps package which provides only the store (plus anything else it needs to function).
The store did update the device health services package, but the other camera package is not listed as an update in there.

Sidenote. The camera app was removed (?) from the store a few days ago, but it was added ack (?). I could not find it even from the store's web page on a desktop browser.
